version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - ./mongo-data:/data/db

  python_app:
    build: .
    container_name: python_container
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8002:8000"
    networks:
      - app_network

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
